### PR TITLE
Update placeholder avatars and source badges

### PR DESCRIPTION
**Pull request by carlosascari**
In `frontend/src/assets/images/users/`
Overview of changes

### CODE REVIEW

**Comment by xdamman** [comment]
Can you add a screenshot of those new avatars to document this PR?

**Comment by xdamman** [comment]
Can we have something nicer for "upload"? Maybe with a Up Arrow?

**Comment by erickrico** [comment]
does this work? 
upload-placeholder

**Comment by xdamman** [comment]
Sure, definitely better. Just make sure that the 3 states are covered (default, hover, pressed) and update the SVG in this PR. Thank you!

**Comment by carlosascari** [comment]
@xdamman The changes you asked have been implemented, they are simple please review, CircleCI failed at `npm run install:debs`

**Comment by xdamman** [comment]
Sorry can't merge if tests don't pass. @sedubois can you take a look? I tried to rerun the tests and they keep failing at that `npm run install:debs` step.

**Comment by sedubois** [comment]
@carlosascari I think you have an old branch, please rebase on master. That was fixed here: https://github.com/OpenCollective/website/pull/197/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R36

**Comment by carlosascari** [comment]
Ready for review and merge

**Pull request merged**
