### PR TITLE
reverting back to tier.name

### PR DESCRIPTION
**Pull request by asood123**

### CODE REVIEW

**Comment by xdamman** [comment]
Can you explain why that change?

**Comment by piamancini** [comment]
because it was pulling from tier.title and it reads "Become a Members"
instead of "Become a Member"

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by piamancini** [comment]
​

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by xdamman** [comment]
Then we should change the title value in the tier definition in the DB. It doesn't feel right to use the name here.

**Comment by asood123** [comment]
tier.name: what goes in the header? Like "Become a backer". Title is what we refer to those group of people as: "Backers". This is how it was until yesterday when we changed it thinking it somehow got flipped in the new design.

**Comment by xdamman** [comment]
This is all very confusing.

To me the name of a tier should be "backer", "sponsor" (the backer tier, the sponsor tier, always lower case).
Then there should be a label which is how it is displayed. Only the label can have space and different case. I thought that "title" was today meant for being the label. And then there is a description.

**Pull request merged**
